### ISSUE TITLE
var вместе с типизацией в цикле for

### ISSUE THREAD

**Issue by KostikShutov** [Quatters/transpiler#22]
https://github.com/Quatters/transpiler/blob/a68d42b8ac9ca834d28fa3b6b2c7a55b73f69b1e/examples/supported_syntax.pas#L38

Pascal abc позволяет компилировать var вместе с явной типизацией в цикле for?

В доке написано:

```
Кроме того, переменную можно описать непосредственно в заголовке цикла:

for переменная: тип := начальное значение to или downto конечное значение do
  оператор

или

for var переменная := начальное значение to или downto конечное значение do
  оператор

В последнем случае используется автоопределение типа переменной по типу начального значения
```

http://pascalabc.net/downloads/pabcnethelp/index.htm?page=LangGuide/Operators/for.html

**Comment by Quatters** [comment]
Позволяет. В выдержке из доков это, видимо, неявно подразумевается. Либо вообще не стали это отражать)

У нас это единственно верная синтаксическая конструкция для использования цикла `for`.

![изображение](https://user-images.githubusercontent.com/73882772/208651673-c9ed7286-abdb-4677-a1f6-85bb55ef6bbd.png)
