### ISSUE TITLE
Реализовать генератор кода

### ISSUE THREAD

**Issue by Quatters** [Quatters/transpiler#7]
Из шпаргалки Шутова:

> Вход: дерево разбора
> Выход: конечный код программы на другом яп
> Разматывается дерево в конечно код яп на основе таблицы преобразований.

**Comment by alicekaeva** [comment]
Примерный план:

- Сделать таблицу сопоставления терминалов 
- Покрыть тестами код, содержащий: циклы, условия, присвоение значений переменным, функции
- Собрать итоговый код на C#

**Comment by KaiLey669** [comment]
В семантическом анализаторе хранить vars_dict, где ключи будут скопами, состоящими из цифры скопа и uuid.
В коде-генераторе надо хранить текущий скоп, дикт, в котором ключи будут цифрами скопов, которые уже встречались, а значения сколько раз уже встречался этот скоп.
Инкрементаем карент_скоп, смотрим в дикт с ключом по карент_скоп и инкрементаем значение.

**Comment by Quatters** [comment]
> В семантическом анализаторе хранить vars_dict, где ключи будут скопами, состоящими из цифры скопа и uuid. В коде-генераторе надо хранить текущий скоп, дикт, в котором ключи будут цифрами скопов, которые уже встречались, а значения сколько раз уже встречался этот скоп. Инкрементаем карент_скоп, смотрим в дикт с ключом по карент_скоп и инкрементаем значение.

Слушай, а вообще лучше даже сделать так. `vars_dict` будет иметь структуру:
```python
{  # глобальный скоп
    0: {  # номер скопа, 0 - глобальный (эти ключи получаются из current_scope, описано ниже)
        1: {  # который раз встретился (дальше описано, как получаются эти ключи)
            'varname1': 'integer',  # имя переменной: тип
            ...
            'varname5': 'real',  
        }
    },
    1: {  # скоп вложенности 1
        1: {  # встретился в исходном коде впервые
            'nested_varname1': 'integer',
            ...
            'nested_varname3': 'real',  
        },
        2: {  # тоже скоп вложенности 1, но встретился в исходном коде второй раз
            'nested_varname1': 'boolean',
            
        },
    },
}
```
В семантике в селфе будет все тот же `current_scope` - текущий скоп, логика с ним уже в принципе есть. Добавится в селф еще один дикт, что-то вроде:

```python
scope_counts = {
    0: 1,  # скоп: сколько раз встречался
    1: 2,
    2: 1,
}
```

Для заполнения такой структуры лучше всего будет сделать отдельный метод примерно с такой логикой:

```python
def save_var(varname, vartype):
    # попробовать взять self.vars_dict[self.current_scope] (безопасно взять ключ из дикта можно с помощью .get(<key>)
    # если такого скопа еще нет, создать 
    # попробовать взять self.vars_dict[self.current_scope][self.scope_counts[self.current_scope]]
    # если скоп с номером self.current_scope, который встречался self.scope_counts[self.current_scope] раз нет, создать
    # положить переменную в self.vars_dict[self.current_scope][self.scope_counts[self.current_scope]]
```

**Comment by Quatters** [comment]
В местах, где инкрементается `self.current_scope` также инкрементать `scope_counts[self.current_scope]`. Если хочешь старый `vars_dict` выпилить, нужно еще будет переделать метод, который проверяет, объявлена ли переменная

**Comment by Quatters** [comment]
Closed via https://github.com/Quatters/transpiler/pull/18
